# Generated by Django 5.1 on 2024-08-12 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "picture",
                    models.FileField(
                        upload_to="Profile_pics", verbose_name="تصویر کاربری"
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارمند",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "حساب کاربری کارمندان",
                "db_table": "profile",
            },
        ),
    ]
