# Generated by Django 5.0.6 on 2024-06-26 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.FloatField(default=0, verbose_name="میزان اعتبار")),
                (
                    "phone",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, verbose_name="وضعیت حساب کاربری"
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="جساب کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "اطلاعات حساب کاربری",
                "db_table": "accountinformation",
            },
        ),
    ]
