# Generated by Django 5.0.6 on 2024-06-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountinformation",
            name="phone",
            field=models.CharField(
                default="0", max_length=11, unique=True, verbose_name="شماره تلفن"
            ),
        ),
    ]
