# Generated by Django 5.1 on 2024-08-12 16:11

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register_Time_Enter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    django_jalali.db.models.jDateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("login", "ورود"), ("Exit", "خروج")],
                        default="Login",
                        max_length=15,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات "),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_enter_exit",
                        to="account.profile",
                        verbose_name="کارمند مورد نظر",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ورود و خروج کارمندان",
                "db_table": "register_time_enter",
            },
        ),
    ]
