# Generated by Django 5.0.6 on 2024-06-24 22:20

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search_Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_name",
                    models.CharField(max_length=150, verbose_name="آدرس دامنه"),
                ),
                (
                    "total_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="متن موجود در صفحه"
                    ),
                ),
                (
                    "total_link",
                    models.TextField(
                        blank=True, null=True, verbose_name="دامنه های موجود"
                    ),
                ),
                (
                    "server",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="سرور"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=100, verbose_name="وضعیت درخواست"),
                ),
                (
                    "time",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ درخواست"
                    ),
                ),
                (
                    "serch_level",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="سطح جستجوی"
                    ),
                ),
                ("summary", models.TextField(verbose_name="خلاصه متن موجود")),
                (
                    "classify",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="دسته بندی"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "دامنه های مورد جستحو",
                "db_table": "search_domain",
                "ordering": ["-id"],
            },
        ),
    ]
