# Generated by Django 5.0.6 on 2024-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guideline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="عنوان راهنمایی"),
                ),
                ("text", models.TextField(verbose_name="متن راهنمایی")),
            ],
            options={
                "verbose_name_plural": "راهنمایی های وبسایت",
                "db_table": "Guideline",
                "ordering": ["-id"],
            },
        ),
    ]
