# Generated by Django 5.1 on 2024-08-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register_time_enter",
            old_name="user",
            new_name="person_user",
        ),
    ]
